---
title: "Title"
author: "Author"
date: "`r Sys.Date()`"
output: mizzourahmd::mizzou_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, comment = "#>")
```

To address our hypothesis and research question we will make use of the “five number summary” suggested by Luke (2015). Luke defined this as the five most useful statistics for describing networks. (a) Size: the number of nodes in the network; (b) Density: the proportion of possible links between nodes that are actually present; (c) Components: the number of subgroups that are not linked to other subgroups within the network; (d) Diameter: the shortest path (in terms of number of links) between the two most separate nodes in the network; and (e) Transitivity (or Clustering Coefficient): the proportion of closed triangles within a network compared to the number of unclosed triangles. Where we make use of the five-number summary, we also break down size into the number of each outlet type, which we have defined as broadcaster, print, and digital-born. These refer to the outlets' heritage (i.e., whether they started out as a broadcaster, print publication, or were ‘born’ online). As such, we refer to the BBC as a broadcaster, even if a particular respondent may have used it online.

We carried out the bulk of the network analysis using the “igraph” package for the statistical language R, as well as UCINET 6. We also make use of network visualizations (see e.g., Figure 2). In the visualizations included here, node size is determined by the weekly news reach of the outlet, and node shading is determined by the outlet type. The layout of each network is determined by the Fruchterman-Reingold algorithm, meaning that nodes are forced to be evenly spaced out with links of roughly equal length.

We expect degrees of cross-platform (online and offline) audience fragmentation and duplication to vary between countries and have specifically hypothesized (H1) that countries like Denmark and the United Kingdom, with centralized media systems, historically strong newspapers, and relatively well-funded public service media will have higher degrees of audience duplication than the other countries in our sample. At a glance the results in Table 2 show that density, and therefore news audience duplication, does indeed vary from country to country. However, the findings are not in line with the expectations behind H1. Network density is highest in Spain (.93), followed by the United States (.87), and France (.80). Density is lower in Germany (.73) and Denmark (.56), and lowest of all in the United Kingdom (.44), where less than half of all possible links are actually present. This is a surprising finding, given our expectation that a combination of strong newspapers and public service media would lead to a high degree of audience duplication. We also see differences in network “diameter” (the shortest path between the two most distant nodes in a network). In Spain, Germany, France, and the United States the diameter is 2, meaning an audience for a particular outlet will be at most only one step removed from overlapping with that of any other outlet in the network. In Denmark and the United Kingdom, the diameter is 3, meaning that some outlets have up to two other nodes between them, suggesting that audiences can be more “distant” from one another.

Table 3 displays the results of a series of t-tests that were used to test for the differences in density between each pair of networks. Overall, the table reveals that in about half of the comparisons, the network densities are significantly different from one another. They are not distinct in every case, but this is to be expected. In other words, this suggests that duplication for cross-platform news audiences varies from country to country. However, while we find clear and significant differences in the degree of audience fragmentation versus duplication across countries, H1 is not supported. Contrary to our expectations, news audiences in Denmark and the United Kingdom, with their more centralized media systems, historically strong newspapers, and relatively well-funded public service media in fact have, in the case of the United Kingdom, more fragmented audiences than all other countries, and in the case of Denmark, more fragmented audiences than Spain and the United States. Explaining these differences, and this surprising finding, will require more research. One possibility is that they can be partially explained by demographic differences within countries (or within samples). For example, the Danish sample contains a larger proportion of university educated individuals (see Table 1). As a partial consequence, frequency of news use is higher in Denmark than in any of the other five countries. We might expect this to produce more overlap between audiences because people are consuming more news, but this does not appear to be the case. It is difficult to map onto the results other potentially relevant measures within the data, such as levels of interest in news and news avoidance, in ways that are illuminating. But, let us note here one distinct feature that sets both Denmark and the United Kingdom apart from the four other media systems—the dominance of a single brand with very high cross-platform reach. In Denmark, 77.92% of respondents use DR online and/or offline, and in the United Kingdom, similarly, 77.72% use BBC online and/or offline, and a significant number of these users did not report using any other sources of news in the last week. The most widely used news source in each of other four countries has a much lower cross-platform reach, ranging from 36.77% (Fox News in the United States) to 56.36% (ARD in Germany).

Next, we turn to the question of whether audience duplication online differs from audience duplication offline (RQ1). Visualizations of the online and offline networks are contained in Figures A1 and B1. Network statistics can be found in Table 4. The statistics show that for all six countries, the online networks have a higher density score than the offline networks. This suggests greater duplication among online news audiences. The difference is greatest in Germany and the United Kingdom (.2), but smaller in Spain (.06). Again, we can use the bootstrap method to compute standard errors, and then use these to produce a t-statistic. When we do this, we find that the difference is statistically significant in Germany (t(90) = 2.03, p = .04), but not in Denmark (t(90) = 1.15, p = .05), France (t(90) = .95, p = .05), Spain (t(90) = .79, p = .05), the United Kingdom (t(90) = 1.53, p = .05), or the United States (t(90) = .92, p = .05). However, this is most likely due to the small size of the networks producing relatively large standard errors. Therefore, our answer to this research question is that across all six countries in our sample, our analysis consistently finds that online news audience are no more fragmented than offline news audiences.

For those who have feared that the move to a higher choice media environment necessarily leads to less audience duplication and more audience fragmentation, this should be a welcome finding, even though it may seem puzzling that online (as a comparatively higher-choice media environment) is not more fragmented than offline (as a comparatively lower-choice media environment). In fact, we would argue, our results lend support to the more general interpretation of contemporary media use offered by James Webster and his various collaborators, characterized by a surprisingly high degree of overlap underneath a veneer of fragmentation. One reason for this may be that in high-choice environments, the increase in choice is often accompanied by a decrease in associated information “costs” (Downs, 1957), such as time and effort. This, combined with the fact that much online news can be accessed for free, may enable highly motivated individuals to consume news from multiple outlets of different types offering different viewpoints, rather than from, say, a single newspaper to which they are particularly loyal. For those who are less motivated, the rise of platforms such as Facebook are likely to play a critical role. Though some suspect that they reinforce preference-driven loyalties through algorithmic selection in ways that might lower duplication, they may simultaneously enable incidental exposure to news, even as people self-select based on other interests. This has the potential to produce a wider variety of news repertoires among the online news-consuming population, which may be one reason we see lower fragmentation online.



